### ISSUE TITLE
Still be able to "Add to Linear" when one Linear issue already exists

### ISSUE THREAD

**Issue by sarah11918** [delucis/github-to-linear#17]
Current behaviour:

If there is any existing Linear issue (by any person) recognized by the extension, then 
- that (or they!) are shown. Yay! 
- the "Add to Linear" option is no longer available. Boo!

Desired behaviour:
You can ALWAYS "Add to Linear" and create a fresh Issue! The fact that Chris has washed his hands of this PR doesn't mean there's not still work for SARAH to do!

**Comment by delucis** [comment]
Thanks, this also crossed my mind and I agree it’s a good idea.

Do you think it’s reasonable for the add option to be less prominent once there’s already at least one issue? For example, something like this?

<img width="341" alt="image" src="https://user-images.githubusercontent.com/357379/229623185-ae43f7e5-672d-46ee-a9d4-696946e0bb81.png">

**Comment by sarah11918** [comment]
Yup, I think it's entirely reasonable!
