### ISSUE TITLE
Fix - Linear issues on pull req list seems wrecked

### ISSUE THREAD

**Issue by jimmyh-onepilot** [delucis/github-to-linear#31]
<img width="1176" alt="Capture d’écran 2024-05-23 à 15 13 02" src="https://github.com/delucis/github-to-linear/assets/90448597/8f703d83-e2ce-4a9e-85e2-f731f4e1c924">

Happening since today only, the related Linear issues should be only one that is really linked to this pull req.

- Did I miss something?

**Comment by ryansdowning** [comment]
Also encountering this bug, starting today. Seeing it on all issues and PRs (including this issue itself).

**Comment by prestonvanloon** [comment]
Same

**Comment by delucis** [comment]
Thanks for the issue — I’m seeing it too. Looks like some change to the Linear API broke issue filtering entirely.

Sorry for the inconvenience — looking to see if there’s a workaround.

**Comment by delucis** [comment]
Haven’t immediately found a way to get Linear’s GraphQL API to return issues like the query has been until today. Kind of hoping maybe it’s a bug on their end that will resolve itself and I’ve written to Linear support to ask.

In the meantime, I’ve published a v0.6.1 of the extension which mitigates the impact of this change by limiting the maximum Linear issues returned to 5. For now they’ll still be whatever random issues Linear feels like returning, but at least they won’t totally wreck the GitHub UI. Fingers crossed this works itself out in the next few days 🤞 

If not, I’ll circle back and see how to best restore something like the previous behaviour.

(v0.6.1 is available now for Firefox and Chrome users. ~~You might need to wait a little longer if you’re using Chrome. Extension review always takes a bit longer for the Chrome Web Store.~~)

**Comment by ryansdowning** [comment]
Appreciate your fast response to this issue. I noticed the official [Linear SDK](https://www.npmjs.com/package/@linear/sdk) has not been updated in the last 3 weeks, so I also think it may be a bug on their end.

**Comment by delucis** [comment]
Noting here so I don’t forget:

Played around with the [Linear API explorer](https://studio.apollographql.com/public/Linear-API/variant/current/explorer) and the change appears to be in how their filter handles `or` queries.

The extension builds a query that looks a bit like this:

```graphql
{
  issueSearch(
    filter: {
      or: [
        { description: { containsIgnoreCase: $identifier } }
        { title: { containsIgnoreCase: $identifier } }
        { title: { containsIgnoreCase: $url } }
        { attachments: { url: { containsIgnoreCase: $url } } }
      ]
    }
  ) {
    # ...
  }
}
```

Previously, this returned issues that match AT LEAST 1 of the `or` conditions.
Currently, it seems to return issues that match NONE of the `or` conditions.

Would be possible to recreate the behaviour with multiple queries, but will hold off implementing that as it still feels like a bug on Linear’s end.

**Comment by delucis** [comment]
I’m seeing the queries working correctly again today 🎉 

Please let me know if you see any further issues.
