### ISSUE TITLE
Show link to linear issue in other parts of the pull request

### ISSUE THREAD

**Issue by AbundantSalmon** [delucis/github-to-linear#33]
I would want to show the link to linear issue in other parts of the pull request, not just the main page.

Something I can do a PR for but just wondering if you would be happy with the change, or whether there was design decision not to show the PR in non main pages of the PR.

E.g. 

Linear issue link shows on:
- `https://github.com/delucis/github-to-linear/pull/25`

But a "Add to linear" button shows on:
- `https://github.com/delucis/github-to-linear/pull/25/commits`
- `https://github.com/delucis/github-to-linear/pull/25/checks`
- `https://github.com/delucis/github-to-linear/pull/25/files`

This is particularly a pain point on the `files` section as when reviewing code I would often want to quickly jump to the linear issue to see what the acceptance criteria are.

**Comment by delucis** [comment]
A PR for this would be welcome, sure. Thank you!

**Comment by delucis** [comment]
Added in #34 and released in v0.7.0 — thanks again @AbundantSalmon!
