### ISSUE TITLE
Add support for showing multiple Linear issues if found

### ISSUE THREAD

**Issue by delucis** [delucis/github-to-linear#9]
Currently we show the most recently created Linear issue in the sidebar on GitHub. Linear and GH issues are not 1<>1 — you can have multiple Linear issues for a single GH issue potentially.

It would be good to support expanding the Linear section of the sidebar to show additional issues if found.

Default view could be something like this:

![image](https://user-images.githubusercontent.com/357379/229498847-a99a3a5e-5593-43ac-b0c5-8d7804ef3a54.png)

And expand to multiple cards when clicked.

Other ideas:

- [ ] #12
- [x] Indicate the status of additional issues in the “more issues” link, e.g. using Linear’s progress icons

**Comment by sarah11918** [comment]
Great issue, Chris!
